#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SOURCE_LINE_MAX_LENGTH 80
#define INIT_PHY_SZ 4
#define INIT_LOG_SZ 0

#define START_COMMENT_CHAR ';'
#define START_MACRO_DEF_LEN 3
#define START_MACRO_DEFENITION "mcr"
#define END_MACRO_DEF_LEN 5
#define END_MACRO_DEFENITION "endmcr"

#endif